import figlet from "figlet"
import * as fs from "node:fs"
import * as path from "node:path"

const left = figlet.textSync("MINI", { font: "Small Block", horizontalLayout: "fitted" })
const right = figlet.textSync("CODE", { font: "Small Block", horizontalLayout: "fitted" })

const leftLines = left.split("\n")
const rightLines = right.split("\n")

const code = `// AUTO-GENERATED by scripts/generate-logo.ts — DO NOT EDIT
export const LOGO_LEFT: string[] = ${JSON.stringify(leftLines, null, "\t")};
export const LOGO_RIGHT: string[] = ${JSON.stringify(rightLines, null, "\t")};
`

const outPath = path.join(import.meta.dirname, "..", "src", "modes", "interactive", "logo-generated.ts")
fs.writeFileSync(outPath, code)
console.log(`Generated logo-generated.ts: ${leftLines.length} left lines, ${rightLines.length} right lines`)
