import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const THEME_DIR = path.join(__dirname, "..", "src", "modes", "interactive", "theme");
const EXPORT_HTML_DIR = path.join(__dirname, "..", "src", "core", "export-html");
const VENDOR_DIR = path.join(EXPORT_HTML_DIR, "vendor");
const ASSETS_DIR = path.join(__dirname, "..", "src", "modes", "interactive", "assets");
const PACKAGE_JSON = path.join(__dirname, "..", "package.json");
const README_MD = path.join(__dirname, "..", "README.md");
const CHANGELOG_MD = path.join(__dirname, "..", "CHANGELOG.md");
const DOCS_DIR = path.join(__dirname, "..", "docs");
const EXAMPLES_DIR = path.join(__dirname, "..", "examples");
const INTERNAL_EXTENSIONS_DIR = path.join(__dirname, "..", "..", "internal-extensions");

function readFileContent(filePath: string): string {
	return fs.readFileSync(filePath, "utf-8");
}

function readBinaryFile(filePath: string): string {
	const buf = fs.readFileSync(filePath);
	return buf.toString("base64");
}

function collectDir(dir: string, ext?: string): Record<string, string> {
	const result: Record<string, string> = {};
	if (!fs.existsSync(dir)) return result;
	const entries = fs.readdirSync(dir, { withFileTypes: true });
	for (const entry of entries) {
		const full = path.join(dir, entry.name);
		if (entry.isFile()) {
			if (ext && !entry.name.endsWith(ext)) continue;
			result[entry.name] = readFileContent(full);
		}
	}
	return result;
}

function collectBinaryDir(dir: string): Record<string, string> {
	const result: Record<string, string> = {};
	if (!fs.existsSync(dir)) return result;
	const entries = fs.readdirSync(dir, { withFileTypes: true });
	for (const entry of entries) {
		const full = path.join(dir, entry.name);
		if (entry.isFile()) {
			result[entry.name] = readBinaryFile(full);
		}
	}
	return result;
}

const EMBED_EXCLUDE_DIRS = new Set(["node_modules", "test", "__tests__", ".git"]);
const EMBED_EXCLUDE_FILES = /\.(test|spec)\.(ts|js|mjs|cjs)$|(^|\/)(package-lock\.json|tsconfig\.json|vitest\.config\.ts|\.eslintrc.*|\.prettierrc.*)$/;

function collectDirRecursive(dir: string, basePath: string): Record<string, string> {
	const result: Record<string, string> = {};
	if (!fs.existsSync(dir)) return result;
	const entries = fs.readdirSync(dir, { withFileTypes: true });
	for (const entry of entries) {
		const full = path.join(dir, entry.name);
		const relative = path.join(basePath, entry.name).replace(/\\/g, "/");
		if (entry.isDirectory()) {
			if (EMBED_EXCLUDE_DIRS.has(entry.name)) continue;
			if (entry.name.endsWith("-disabled")) continue;
			Object.assign(result, collectDirRecursive(full, relative));
		} else if (entry.isFile()) {
			if (EMBED_EXCLUDE_FILES.test(entry.name)) continue;
			result[relative] = readFileContent(full);
		}
	}
	return result;
}

const themes = collectDir(THEME_DIR, ".json");
const exportHtml: Record<string, string> = {};
const templateHtml = path.join(EXPORT_HTML_DIR, "template.html");
const templateCss = path.join(EXPORT_HTML_DIR, "template.css");
const templateJs = path.join(EXPORT_HTML_DIR, "template.js");
if (fs.existsSync(templateHtml)) exportHtml["template.html"] = readFileContent(templateHtml);
if (fs.existsSync(templateCss)) exportHtml["template.css"] = readFileContent(templateCss);
if (fs.existsSync(templateJs)) exportHtml["template.js"] = readFileContent(templateJs);
const vendorFiles = collectDir(VENDOR_DIR, ".js");
for (const [k, v] of Object.entries(vendorFiles)) {
	exportHtml[`vendor/${k}`] = v;
}

const assets = collectBinaryDir(ASSETS_DIR);

const pkgJson = fs.existsSync(PACKAGE_JSON) ? readFileContent(PACKAGE_JSON) : "{}";
// Excluding non-essential embedded content to reduce binary size
// const readmeMd = fs.existsSync(README_MD) ? readFileContent(README_MD) : "";
// const changelogMd = fs.existsSync(CHANGELOG_MD) ? readFileContent(CHANGELOG_MD) : "";
// const docs = collectDirRecursive(DOCS_DIR, "docs");
// const examples = collectDirRecursive(EXAMPLES_DIR, "examples");
const internalExtensions = collectDirRecursive(INTERNAL_EXTENSIONS_DIR, "internal-extensions");

const lines: string[] = [
	"// AUTO-GENERATED by scripts/generate-embed.ts — DO NOT EDIT",
	"",
	"export const EMBEDDED_THEMES: Record<string, string> = {",
];
for (const [name, content] of Object.entries(themes)) {
	const escaped = content.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
	lines.push(`  ${JSON.stringify(name)}: \`${escaped}\`,`);
}
lines.push("};");
lines.push("");

lines.push("export const EMBEDDED_EXPORT_HTML: Record<string, string> = {");
for (const [name, content] of Object.entries(exportHtml)) {
	const escaped = content.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
	lines.push(`  ${JSON.stringify(name)}: \`${escaped}\`,`);
}
lines.push("};");
lines.push("");

lines.push("export const EMBEDDED_ASSETS: Record<string, string> = {");
for (const [name, content] of Object.entries(assets)) {
	lines.push(`  ${JSON.stringify(name)}: "${content}",`);
}
lines.push("};");
lines.push("");

const pkgObj = JSON.parse(pkgJson);
const embeddedPkg = JSON.stringify({
	name: pkgObj.name,
	version: pkgObj.version,
	description: pkgObj.description,
	bin: pkgObj.bin,
	piConfig: pkgObj.piConfig,
}, null, 2);
lines.push(`export const EMBEDDED_PACKAGE_JSON = ${JSON.stringify(embeddedPkg)};`);
lines.push("");

// Embed build info from packages/minicode/build-info.js (generated by scripts/generate-build-info.ts)
const BUILD_INFO_PATH = path.resolve(__dirname, "..", "..", "minicode", "build-info.js");
try {
	const buildInfoRaw = fs.readFileSync(BUILD_INFO_PATH, "utf-8");
	const buildVersion = buildInfoRaw.match(/BUILD_VERSION\s*=\s*"([^"]+)"/)?.[1] ?? pkgObj.version;
	const buildDate = buildInfoRaw.match(/BUILD_DATE\s*=\s*"([^"]+)"/)?.[1] ?? new Date().toISOString();
	const gitCommit = buildInfoRaw.match(/GIT_COMMIT\s*=\s*"([^"]+)"/)?.[1] ?? "unknown";
	const isStable = buildInfoRaw.match(/IS_STABLE\s*=\s*(true|false)/)?.[1] === "true";
	lines.push(`export const EMBEDDED_BUILD_INFO = ${JSON.stringify(JSON.stringify({ version: buildVersion, date: buildDate, commit: gitCommit, stable: isStable }))};`);
} catch {
	lines.push(`export const EMBEDDED_BUILD_INFO = "";`);
}
lines.push("");

lines.push("export const EMBEDDED_EXTENSIONS_MANIFEST = true;");
lines.push("");

const WASM_PATH = path.join(__dirname, "..", "dist", "photon_rs_bg.wasm");
if (fs.existsSync(WASM_PATH)) {
	const wasmBase64 = readBinaryFile(WASM_PATH);
	lines.push(`export const EMBEDDED_WASM_BASE64 = "${wasmBase64}";`);
} else {
	lines.push(`export const EMBEDDED_WASM_BASE64 = "";`);
}
lines.push("");

// Excluding non-essential embedded content to reduce binary size
// const escapedReadme = readmeMd.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
// lines.push(`export const EMBEDDED_README = \`${escapedReadme}\`;`);
// lines.push("");

// const escapedChangelog = changelogMd.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
// lines.push(`export const EMBEDDED_CHANGELOG = \`${escapedChangelog}\`;`);
// lines.push("");

// lines.push("export const EMBEDDED_DOCS: Record<string, string> = {");
// for (const [name, content] of Object.entries(docs)) {
// 	const escaped = content.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
// 	lines.push(`  ${JSON.stringify(name)}: \`${escaped}\`,`);
// }
// lines.push("};");
// lines.push("");

// lines.push("export const EMBEDDED_EXAMPLES: Record<string, string> = {");
// for (const [name, content] of Object.entries(examples)) {
// 	const escaped = content.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
// 	lines.push(`  ${JSON.stringify(name)}: \`${escaped}\`,`);
// }
// lines.push("};");
// lines.push("");

lines.push("export const EMBEDDED_INTERNAL_EXTENSIONS: Record<string, string> = {");
for (const [name, content] of Object.entries(internalExtensions)) {
	const escaped = content.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
	lines.push(`  ${JSON.stringify(name)}: \`${escaped}\`,`);
}
lines.push("};");
lines.push("");

// Empty placeholders for excluded content (referenced by other code)
lines.push(`export const EMBEDDED_README = "";`);
lines.push("");
lines.push(`export const EMBEDDED_CHANGELOG = "";`);
lines.push("");
lines.push(`export const EMBEDDED_DOCS: Record<string, string> = {};`);
lines.push("");
lines.push(`export const EMBEDDED_EXAMPLES: Record<string, string> = {};`);
lines.push("");

const outPath = path.join(__dirname, "..", "src", "embedded.ts");
fs.writeFileSync(outPath, lines.join("\n"));
console.log(`Generated embedded.ts:`);
console.log(`  ${Object.keys(themes).length} themes`);
console.log(`  ${Object.keys(exportHtml).length} templates`);
console.log(`  ${Object.keys(assets).length} assets`);
console.log(`  ${Object.keys(internalExtensions).length} internal extensions`);
console.log(`  (Excluded: README, CHANGELOG, DOCS, EXAMPLES to reduce binary size)`);
