/** Non-model keys in config.agent — preserved when clearing all overrides. */
export const CONFIG_AGENT_NON_MODEL_KEYS = [
	"default",
	"forceBackground",
	"graceTurns",
	"showCost",
	"showTools",
	"showTurns",
	"showInput",
	"showOutput",
	"showContext",
	"showTime",
	"deltaInputTokens",
	"widgetMaxLines",
	"widgetMaxLinesCompact",
	"widgetDescLengthFull",
	"widgetDescLengthCompact",
	"widgetCompact",
	"widgetShortcut",
	"systemPromptMode",
	"includeContextFiles",
	"defaultThinking",
	"defaultMaxTurns",
	"loadSkillsImplicitly",
	"loadExtensionsImplicitly",
	"disableDefaultAgents",
	"outputThinkingBufferSize",
];
