// Logo data generated by scripts/generate-logo.ts
// MINI (left) = gray, CODE (right) = softWhite
import type { Component } from "@earendil-works/pi-tui";
import { LOGO_LEFT, LOGO_RIGHT } from "./logo-generated.ts";
import { theme } from "./theme/theme.ts";

let cachedLogoStr: string | null = null;

export function getAsciiLogo(): string {
	if (cachedLogoStr) return cachedLogoStr;

	const maxLen = Math.max(LOGO_LEFT.length, LOGO_RIGHT.length);
	const lines: string[] = [];
	for (let i = 0; i < maxLen; i++) {
		const left = (LOGO_LEFT[i] || "").padEnd(11);
		const right = LOGO_RIGHT[i] || "";
		// MINI in gray, CODE in softWhite
		lines.push(theme.fg("dim", left) + theme.fg("softWhite", right));
	}
	cachedLogoStr = lines.join("\n");
	return cachedLogoStr;
}

export function getAsciiLogoCentered(width: number): string {
	const maxLen = Math.max(LOGO_LEFT.length, LOGO_RIGHT.length);

	// Calculate actual logo width (excluding ANSI codes)
	let logoWidth = 0;
	for (let i = 0; i < maxLen; i++) {
		const left = LOGO_LEFT[i] || "";
		const right = LOGO_RIGHT[i] || "";
		const lineWidth = left.length + 11 + right.length; // 16 is padding
		if (lineWidth > logoWidth) logoWidth = lineWidth;
	}

	const leftPad = Math.max(0, Math.floor((width - logoWidth) / 2) - 3);
	const padStr = " ".repeat(leftPad);

	const lines: string[] = [];
	for (let i = 0; i < maxLen; i++) {
		const left = (LOGO_LEFT[i] || "").padEnd(11);
		const right = LOGO_RIGHT[i] || "";
		lines.push(padStr + theme.fg("dim", left) + theme.fg("softWhite", right));
	}
	return lines.join("\n");
}

/**
 * Dynamic logo component that re-centers on terminal resize
 */
export class LogoComponent implements Component {
	private cachedWidth: number = 0;
	private cachedLines: string[] = [];
	private suffix: string = "";

	constructor(suffix: string = "") {
		this.suffix = suffix;
	}

	render(width: number): string[] {
		if (width === this.cachedWidth && this.cachedLines.length > 0) {
			return this.cachedLines;
		}
		this.cachedWidth = width;
		const lines = getAsciiLogoCentered(width).split("\n");
		// Append suffix to the last line of the logo
		if (lines.length > 0 && this.suffix) {
			lines[lines.length - 1] += this.suffix;
		}
		this.cachedLines = lines;
		return this.cachedLines;
	}

	invalidate(): void {
		this.cachedWidth = 0;
		this.cachedLines = [];
	}
}

export const logos = {
	classic: { left: LOGO_LEFT, right: LOGO_RIGHT },
} as const;

export type LogoKey = keyof typeof logos;
