import { execSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

function gitDescribe(): string {
	try {
		return execSync("git describe --tags --always --dirty", {
			encoding: "utf8",
			timeout: 3000,
		}).trim();
	} catch {
		return "unknown";
	}
}

function buildTimestamp(): string {
	const now = new Date();
	const y = now.getFullYear();
	const m = String(now.getMonth() + 1).padStart(2, "0");
	const d = String(now.getDate()).padStart(2, "0");
	const h = String(now.getHours()).padStart(2, "0");
	const min = String(now.getMinutes()).padStart(2, "0");
	return `${y}${m}${d}${h}${min}`;
}

function gitCommit(): string {
	try {
		return execSync("git rev-parse --short HEAD", {
			encoding: "utf8",
			timeout: 3000,
		}).trim();
	} catch {
		return "unknown";
	}
}

/**
 * Parse git-describe output and determine build info.
 *
 * Stable (exact tag match):   "v0.1.0"               → version "0.1.0", isStable true
 * Dev (commits after tag):    "v0.1.0-5-gabc"        → version "0.1.0-5-202607041828", isStable false
 * Dirty (uncommitted):        "v0.1.0-dirty"          → version "0.1.0-dirty", isStable false
 * No tags:                   "abc1234"                → version "0.0.0-202607041828", isStable false
 */
function parseBuildInfo(describe: string, timestamp: string): { version: string; isStable: boolean } {
	// Exact tag match: vX.Y.Z or vX.Y.Z-rc.N etc. (exclude -dirty, handled separately)
	const exactTag = /^v(\d+\.\d+\.\d+(-(?!dirty)[a-zA-Z0-9.]+)?)$/;
	const mExact = describe.match(exactTag);
	if (mExact) {
		return { version: mExact[1]!, isStable: !mExact[2] };
	}

	// Tag with commits: vX.Y.Z-N-gHASH
	const tagCommits = /^v(\d+\.\d+\.\d+)-(\d+)-g([0-9a-f]+)(-dirty)?$/;
	const mCommits = describe.match(tagCommits);
	if (mCommits) {
		const suffix = mCommits[4] ? "-dirty" : "";
		return { version: `${mCommits[1]}-${mCommits[2]}-${timestamp}${suffix}`, isStable: false };
	}

	// Dirty exact tag: vX.Y.Z-dirty → treat as stable release (dirty tree doesn't affect version)
	const dirtyTag = /^v(\d+\.\d+\.\d+)-dirty$/;
	const mDirty = describe.match(dirtyTag);
	if (mDirty) {
		return { version: mDirty[1]!, isStable: true };
	}

	// Fallback: just a hash (no tags), or unknown
	return { version: `0.0.0-${timestamp}`, isStable: false };
}

function generate(): void {
	const describe = gitDescribe();
	const ts = buildTimestamp();
	const commit = gitCommit();
	const { version, isStable } = parseBuildInfo(describe, ts);
	const buildDate = new Date().toISOString();

	const outDir = path.resolve(__dirname, "..", "packages", "minicode");
	fs.mkdirSync(outDir, { recursive: true });

	const tsLines: string[] = [
		"// Auto-generated by scripts/generate-build-info.ts — DO NOT EDIT",
		`export const BUILD_VERSION: string = ${JSON.stringify(version)};`,
		`export const BUILD_DATE: string = ${JSON.stringify(buildDate)};`,
		`export const GIT_COMMIT: string = ${JSON.stringify(commit)};`,
		`export const IS_STABLE: boolean = ${JSON.stringify(isStable)};`,
		"",
	];

	fs.writeFileSync(path.join(outDir, "build-info.ts"), tsLines.join("\n"));

	const jsLines: string[] = [
		"// Auto-generated by scripts/generate-build-info.ts — DO NOT EDIT",
		`export const BUILD_VERSION = ${JSON.stringify(version)};`,
		`export const BUILD_DATE = ${JSON.stringify(buildDate)};`,
		`export const GIT_COMMIT = ${JSON.stringify(commit)};`,
		`export const IS_STABLE = ${JSON.stringify(isStable)};`,
		"",
	];

	fs.writeFileSync(path.join(outDir, "build-info.js"), jsLines.join("\n"));

	const dtsLines: string[] = [
		"// Auto-generated by scripts/generate-build-info.ts — DO NOT EDIT",
		`export const BUILD_VERSION: string;`,
		`export const BUILD_DATE: string;`,
		`export const GIT_COMMIT: string;`,
		`export const IS_STABLE: boolean;`,
		"",
	];

	fs.writeFileSync(path.join(outDir, "build-info.d.ts"), dtsLines.join("\n"));

	console.log(`Generated build-info: version=${version} stable=${isStable}`);
}

generate();
